name: Deploy Application
on: [workflow_dispatch]
jobs: 
  testing:
    runs-on: ubuntu-latest
    steps: 
      - name: First get the Code
        uses: actions/checkout@v4.2.2  
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint
  
      - name: Run Tests
        run: npm run test
    
  deployment:
    runs-on: ubuntu-latest
    needs: testing
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4.2.2
     - name: Install dependencies
       run: npm ci
     - name: Build Application
       run: | 
        echo "Building application..."
        npm run build
        echo "Build completed successfully!"
     - name: Deploy Application
       run: |
            echo "Deploying application..."
            echo "taking Confirmation...."
            echo "Application deployed successfully!"
        